THETA_CONFIG = {
    "latency": 50,
    "input_opts": [
        "-f",
        "v4l2",
        "-input_format",
        "mjpeg",
        "-video_size",
        "1920x960",
        "-framerate",
        "30",
        "-i",
        "/dev/video0",
    ],
    "output_opts": [
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-tune",
        "zerolatency",
        "-crf",
        "18",
        "-f",
        "mpegts",
    ],
}
